###  |---- SERVER STATUS ----|

### Check the status of the service
get https://europe-west2-neoinbox.cloudfunctions.net/api/
Content-Type: application/json







###  |---- WATCH MANAGEMENT ----|

### Renew the watch expiration time
post https://europe-west2-neoinbox.cloudfunctions.net/api/watch-renew
Content-Type: application/json

{}



### Enable the watch
post https://europe-west2-neoinbox.cloudfunctions.net/api/watch-enable
Content-Type: application/json

{
	"historyId": "4949",
	"expiration": 1737104318,
	"userId": "testing_user_id"
}



### Disable the watch
post https://europe-west2-neoinbox.cloudfunctions.net/api/watch-disable
Content-Type: application/json

{
	"userId": "testing_user_id"
}



### Check the status of the watch
get https://europe-west2-neoinbox.cloudfunctions.net/api/watch-status?userId=testing_user_id







###  |---- OAUTH MANAGEMENT----|

### Get the Google OAuth URL
post https://europe-west2-neoinbox.cloudfunctions.net/api/auth-url
Content-Type: application/json

{
	"scopes": [
		"https://www.googleapis.com/auth/calendar.events.freebusy",
		"https://www.googleapis.com/auth/calendar.calendarlist.readonly"
	]
}



### Get the Google OAuth token
post https://europe-west2-neoinbox.cloudfunctions.net/api/auth-token
Content-Type: application/json

{
    "code": "4%2F0AQSTgQF1QtGWvcdhGQnp6qSn6FJZCseCjNqgPcNgenEocHb33fF4g8YMLHlmUBfbhtCYsA"
}







###  |---- MACROS MANAGEMENT----|

### Create a new macro

post https://europe-west2-neoinbox.cloudfunctions.net/api/macro-create
Content-Type: application/json

{
	"userId": "testing_user_id",
	"name": "Inbox_Attachment_Ideas",
	"labels": [
		{
			"name" : "INBOX",
			"id" : "INBOX"
		},
		{
			"name" : "UNREAD",
			"id" : "UNREAD"
		}
	],
	"actionType": "attachment",
	"service": "google-drive",
	"remainder": [
		{
		"name": "Ideas",
		"id": "1ruy5kcRrX2ExQepHJbAnF2NcUZCff1pE"
		}
	]
}



### Get the macro (name) of the user (userId)
get https://europe-west2-neoinbox.cloudfunctions.net/api/macro-get?userId=testing_user_id&name=Inbox_Attachment_Ideas



### Get all the macros of the user
get https://europe-west2-neoinbox.cloudfunctions.net/api/macro-get-all?userId=testing_user_id



### Get all macros filtered by labels
get https://europe-west2-neoinbox.cloudfunctions.net/api/macro-get-all-filtered?userId=testing_user_id&labelIds=INBOX,UNREAD